apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  selector:
    component: kibana
  ports:
  - name: http
    port: 5601 #80
    targetPort: http
  type:  NodePort
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: kibana
#  labels:
#    app: kibana
#spec:
#  ports:
#    - port: 80 
#  selector:
#    app: kibana 
#    tier: frontend
#  type: LoadBalancer
