#apiVersion: v1
#kind: Pod
#metadata:
#  name: nginx
#  labels:
#    app: nginx
##  namespace: logging
#spec:
##  nodeSelector:
##    kubernetes.io/hostname: kworker-1 
#  containers:
#  - name: 1st
#    image: nginx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        fluentbit.io/parser: nginx
       # mycustom: annotation
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.9.1
        ports:
        - containerPort: 80
